### ISSUE TITLE
Command for displaying LagrangianSystem and HamiltonianSystem

### ISSUE THREAD

**Issue by finmod** [JuliaGNI/EulerLagrange.jl#8]
A command for displaying or systematic printing of a system before sending to the solver would be good. It may already be there but I dont know where.

**Comment by michakraus** [comment]
Thanks for the suggestion. This is a very good point. I added `Base.show` methods for both `HamiltonianSystem` and `LagrangianSystem`. It is not really pretty, but it gets the job done.
